<a href="https://colab.research.google.com/github/SasanduG/Care-Band/blob/main/02_Indexing_and_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Indexing and Slicing in NumPy

In [2]:
import numpy as np

### Indexing

In [3]:
arr = np.array([1,2,3,4])
arr[1]

np.int64(2)

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [6]:
## Bad way

arr2[0][2] #3, returns an np.int64 object

np.int64(3)

In [9]:
## Good way
arr2[0,2]

np.int64(3)

In [ ]:
### Conceptual behaviour  of arr2[0][2]

row = arr2[0]
value = arr2[1]

### Slicing

In [13]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,9,10,11]
])

In [14]:
arr[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [20]:
arr[::2,::2] # ::2 means start = 0, until end, step = 2

array([[ 1,  3],
       [ 8, 10]])

In [23]:
arr[::2,::3]

array([[ 1,  4],
       [ 8, 11]])

In [24]:
arr[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [26]:
arr[:2,2:]

array([[3, 4],
       [7, 8]])